// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQ8i_3VdLHe-vrDsP60n2THDqBuw_Xzo',
    appId: '1:871924616185:web:72933ae9456d075f1f4b28',
    messagingSenderId: '871924616185',
    projectId: 'atarist-notes-app',
    authDomain: 'atarist-notes-app.firebaseapp.com',
    storageBucket: 'atarist-notes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoA6VflNv9M7SKcDswi9o43YY7AaweuZg',
    appId: '1:871924616185:android:7a42311e2eab926c1f4b28',
    messagingSenderId: '871924616185',
    projectId: 'atarist-notes-app',
    storageBucket: 'atarist-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7cexwVKYHYRw25dzDBhJ6Il7eTVR8y-s',
    appId: '1:871924616185:ios:0e69b03c935b18d91f4b28',
    messagingSenderId: '871924616185',
    projectId: 'atarist-notes-app',
    storageBucket: 'atarist-notes-app.appspot.com',
    iosClientId: '871924616185-a8qijrkjlv4hvl3hcnbnqsbgqvop88rb.apps.googleusercontent.com',
    iosBundleId: 'com.atarist.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7cexwVKYHYRw25dzDBhJ6Il7eTVR8y-s',
    appId: '1:871924616185:ios:0e69b03c935b18d91f4b28',
    messagingSenderId: '871924616185',
    projectId: 'atarist-notes-app',
    storageBucket: 'atarist-notes-app.appspot.com',
    iosClientId: '871924616185-a8qijrkjlv4hvl3hcnbnqsbgqvop88rb.apps.googleusercontent.com',
    iosBundleId: 'com.atarist.mynotes',
  );
}
